SUBDIR+= intro
SUBDIR+= foundations
SUBDIR+= crypto
SUBDIR+= auth
SUBDIR+= ac
SUBDIR+= accountability
SUBDIR+= trustcomp
SUBDIR+= software
SUBDIR+= conclusion

SUBDIR_GOALS=all print clean distclean


INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/subdir.mk
