SUBDIR+= intro
SUBDIR+= foundations
SUBDIR+= crypto
SUBDIR+= auth
SUBDIR+= ac
SUBDIR+= accountability
SUBDIR+= trustcomp
SUBDIR+= software
SUBDIR+= conclusion

SUBDIR_ALL_GOALS=no

.PHONY: all print clean distclean
all print clean distclean: ${SUBDIR}


INCLUDE_MAKEFILES=../makefiles
include ${INCLUDE_MAKEFILES}/subdir.mk
