OUT+= 	introduction.html
OUT+= 	foundations-usability.html
OUT+= 	infotheory-crypto.html
OUT+= 	auth.html
OUT+= 	ac.html
OUT+= 	accountability.html
OUT+= 	trustcomp.html
OUT+= 	software.html
OUT+= 	conclusion.html


.PHONY: all
all: ${OUT}


.PHONY: clean
clean:
	${RM} ${OUT}


INCLUDE_MAKEFILES?=../makefiles
include ${INCLUDE_MAKEFILES}/doc.mk

